 CREATE DATABASE Multas_1
USE Multas_1

CREATE TABLE Multa(
Id_multa INT NOT NULL PRIMARY KEY,
Placa VARCHAR (15)NOT NULL,
Marca VARCHAR (25)NOT NULL,
Color VARCHAR (25)NOT NULL,
Modelo VARCHAR (25)NOT NULL,
Descripcion Varchar(max)NOT NULL,
Sub_total INT NOT NULL,
Descuento INT NOT NULL,
Total INT 
)

SELECT * FROM Multa

CREATE TABLE Tipo_Usu(
Id_tipo_usu INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(10)NOT NULL
)

CREATE TABLE Usuario(
Id_usuario INT NOT NULL PRIMARY KEY,
Nombre VARCHAR (25)NOT NULL,
Contraseña VARCHAR (25)NOT NULL,
Id_cliente INT NOT NULL REFERENCES Tipo_Usu)

INSERT INTO Tipo_Usu VALUES(1,'ADMIN')
INSERT INTO Tipo_Usu VALUES(2,'PUBLICO')

INSERT INTO Usuario VALUES(1,'Carlos','12',1)
INSERT INTO Usuario VALUES(2,'Jacobo','12',2)

SELECT * FROM Tipo_Usu
SELECT *FROM Usuario 
